spring:
  cloud:
    gateway:
      routes:
        - id: no-auth-server
          uri: http://localhost:60000/
          predicates:
            - Path=/api/user/login/**, /api/manager/login/**
          filters:
            - RewritePath=/api/user/login/(?<remaining>.*), /v1/no-auth/$\{remaining}
            - RewritePath=/api/manager/login/(?<remaining>.*), /v1/no-auth/$\{remaining}

        - id: user-server
          uri: http://localhost:50001/
          predicates:
            - Path=/api/user/**, /api/manager/**
          filters:
            - name: CheckJwtFilterFactory
            - RewritePath=/api/user/(?<remaining>.*), /v1/user/$\{remaining}
            - RewritePath=/api/manager/(?<remaining>.*), /v1/manager/$\{remaining}

        - id: menu-server
          uri: http://localhost:50002/
          predicates:
            - Path=/api/user/menu/**, /api/manager/menu/**
          filters:
            - name: CheckJwtFilterFactory
            - RewritePath=/api/user/menu/(?<remaining>.*), /v1/menu/user/$\{remaining}
            - RewritePath=/api/manager/menu/(?<remaining>.*), /v1/menu/manager/$\{remaining}

        - id: image-server
          uri: http://localhost:60001/
          predicates:
            - Path=/api/image/**
          filters:
            - RewritePath=/api/image/(?<remaining>.*), /v1/image/$\{remaining}