# env
spring:
  profiles:
    include: keycloak, client, eureka

  application:
    name: no-auth-client

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasypt

server:
  port: 60000