# env
spring:
  profiles:
    include: db, dbAuth, slack, monitor, keycloak

  application:
    name: kjj-no-auth

  # data.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
          show_sql: true
          format_sql: true
  sql:
    init:
      mode: never

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasypt

server:
  port: 60000
---
spring:
  config:
    activate:
      on-profile: prod

  # data.sql
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false