# env
spring:
  profiles:
    include: monitor, keycloak, client

  application:
    name: kjj-no-auth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasypt

server:
  port: 60000