# Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
      base-path: ENC(h4qjm5pWaxCVhFLgnXyap4AAouGEsy7Gjm+EyPmGTcY=)

  endpoint:
    health:
      enabled: true

my:
  actuator:
    path: ENC(3aT/vVhONgwb9fUNyYcql3dB4otCYZzQvCWi4j5GLjE=)