spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.uri-dev}
    username: ${mysql.username}
    password: ${mysql.password}
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${mysql.uri}