# Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
      base-path: ENC(7Br3hhVq66/sAE7e8i8KARuAE36elNWc5NBqKIXGaEs=)

  endpoint:
    health:
      enabled: true

my:
  actuator:
    path: ENC(3aT/vVhONgwb9fUNyYcql3dB4otCYZzQvCWi4j5GLjE=)