server:
  port: 50005

spring:
  profiles:
    include: client, eureka

  application:
    name: planner-client

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test1234
    url: jdbc:mysql://db-mysql:3306/kjj_planner?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/kjj_planner?useSSL=false&allowPublicKeyRetrieval=true