server:
  port: 55555

kjj:
  client:
    order:
      host: http://user:50001
    user:
      host: http://user:50001
    menu:
      host: http://menu:50002
---
spring:
  config:
    activate:
      on-profile: dev
kjj:
  client:
    order:
      host: http://localhost:50001
    user:
      host: http://localhost:50001
    menu:
      host: http://localhost:50002