spring:
  profiles:
    include: eureka
  application:
    name: client

server:
  port: 55555

kjj:
  client:
    order:
      host: http://USER-CLIENT
    user:
      host: http://USER-CLIENT
    menu:
      host: http://MENU-CLIENT
---
spring:
  config:
    activate:
      on-profile: dev
kjj:
  client:
    order:
      host: http://localhost:50001
    user:
      host: http://localhost:50001
    menu:
      host: http://localhost:50002